### ISSUE TITLE
MS Marco flagged as non-public

### ISSUE THREAD

**Issue by EmGarr** [google-deepmind/loft#2]
Thanks for this awesome benchmark.

In your README.md you define MS Marco as non-public while it is freely available on [beir](https://github.com/beir-cellar/beir?tab=readme-ov-file) at this [url](https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/msmarco.zip).

Is it because of the licensing (non-commercial research purposes) or is just an error ?

Thanks :D

**Comment by jhyuklee** [comment]
It is because of the licensing. We will upload a script where you can download the dataset from the original source and preprocess it in the same way as we used.
